### ISSUE TITLE
Stream should not be able to refer to itself

### ISSUE THREAD

**Issue by kmaehashi** [sensorbee/sensorbee#154]
Currently the following BQL is accepted; nothing happens, but runfile blocks forever.

```
CREATE STREAM mystream AS SELECT RSTREAM * FROM mystream [RANGE 1 TUPLES];
```

I think it is better to report error in such case.

**Comment by nobu-k** [comment]
https://github.com/sensorbee/sensorbee/blob/7439272c3f3c7c69ac1a02284a3c1680c8731b69/bql/topology_builder_test.go#L249

This test wasn't working correctly because it captured a completely different error. The error it actually gets is that `s` already exists as a source, not that `FROM` has the same name as the stream to be created. I'll fix this issue.
